// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetLogFile(path: string): $CancellablePromise<$models.LogFile | null> {
    return $Call.ByID(1607372547, path).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListLogFiles(dir: string): $CancellablePromise<$models.LogDirectoryResult | null> {
    return $Call.ByID(966221630, dir).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListRemoteLogFiles(server: $models.RemoteServer): $CancellablePromise<$models.LogDirectoryResult | null> {
    return $Call.ByID(2283783740, server).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ReadRemoteTail(server: $models.RemoteServer, path: string, lines: number, encoding: string): $CancellablePromise<$models.LogContentResult | null> {
    return $Call.ByID(690007, server, path, lines, encoding).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ReadTail(path: string, lines: number, encoding: string): $CancellablePromise<$models.LogContentResult | null> {
    return $Call.ByID(2684180761, path, lines, encoding).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ReadTailUpdate(path: string, offset: number, encoding: string): $CancellablePromise<$models.TailUpdateResult | null> {
    return $Call.ByID(2974869080, path, offset, encoding).then(($result: any) => {
        return $$createType7($result);
    });
}

export function SearchInFile(path: string, options: $models.SearchOptions): $CancellablePromise<$models.SearchResult | null> {
    return $Call.ByID(1750734818, path, options).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SearchInFiles(files: $models.LogFile[], options: $models.SearchOptions): $CancellablePromise<$models.MultiSearchResult | null> {
    return $Call.ByID(3604158787, files, options).then(($result: any) => {
        return $$createType11($result);
    });
}

export function SearchRemoteInFile(server: $models.RemoteServer, path: string, options: $models.SearchOptions): $CancellablePromise<$models.SearchResult | null> {
    return $Call.ByID(879999728, server, path, options).then(($result: any) => {
        return $$createType9($result);
    });
}

// Private type creation functions
const $$createType0 = $models.LogFile.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.LogDirectoryResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.LogContentResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.TailUpdateResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.SearchResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.MultiSearchResult.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
