// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class FileSearchResult {
    "file": LogFile;
    "keyword": string;
    "hits": SearchHit[];
    "hitCount": number;
    "limited": boolean;
    "scanned": number;
    "warning": string;

    /** Creates a new FileSearchResult instance. */
    constructor($$source: Partial<FileSearchResult> = {}) {
        if (!("file" in $$source)) {
            this["file"] = (new LogFile());
        }
        if (!("keyword" in $$source)) {
            this["keyword"] = "";
        }
        if (!("hits" in $$source)) {
            this["hits"] = [];
        }
        if (!("hitCount" in $$source)) {
            this["hitCount"] = 0;
        }
        if (!("limited" in $$source)) {
            this["limited"] = false;
        }
        if (!("scanned" in $$source)) {
            this["scanned"] = 0;
        }
        if (!("warning" in $$source)) {
            this["warning"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileSearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FileSearchResult {
        const $$createField0_0 = $$createType0;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("file" in $$parsedSource) {
            $$parsedSource["file"] = $$createField0_0($$parsedSource["file"]);
        }
        if ("hits" in $$parsedSource) {
            $$parsedSource["hits"] = $$createField2_0($$parsedSource["hits"]);
        }
        return new FileSearchResult($$parsedSource as Partial<FileSearchResult>);
    }
}

export class LogContentResult {
    "path": string;
    "lines": LogLine[];
    "totalRead": number;
    "truncated": boolean;
    "warning": string;
    "size": number;

    /** Creates a new LogContentResult instance. */
    constructor($$source: Partial<LogContentResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("lines" in $$source)) {
            this["lines"] = [];
        }
        if (!("totalRead" in $$source)) {
            this["totalRead"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("warning" in $$source)) {
            this["warning"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogContentResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LogContentResult {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField1_0($$parsedSource["lines"]);
        }
        return new LogContentResult($$parsedSource as Partial<LogContentResult>);
    }
}

export class LogDirectoryResult {
    "root": string;
    "files": LogFile[];
    "warnings": string[];

    /** Creates a new LogDirectoryResult instance. */
    constructor($$source: Partial<LogDirectoryResult> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogDirectoryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LogDirectoryResult {
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField2_0($$parsedSource["warnings"]);
        }
        return new LogDirectoryResult($$parsedSource as Partial<LogDirectoryResult>);
    }
}

export class LogFile {
    "name": string;
    "path": string;
    "size": number;
    "modTime": string;

    /** Creates a new LogFile instance. */
    constructor($$source: Partial<LogFile> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogFile instance from a string or object.
     */
    static createFrom($$source: any = {}): LogFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogFile($$parsedSource as Partial<LogFile>);
    }
}

export class LogLine {
    "number": number;
    "text": string;
    "level": string;

    /** Creates a new LogLine instance. */
    constructor($$source: Partial<LogLine> = {}) {
        if (!("number" in $$source)) {
            this["number"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogLine instance from a string or object.
     */
    static createFrom($$source: any = {}): LogLine {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogLine($$parsedSource as Partial<LogLine>);
    }
}

export class MultiSearchResult {
    "keyword": string;
    "files": FileSearchResult[];
    "filesScanned": number;
    "hitCount": number;
    "limited": boolean;
    "warnings": string[];

    /** Creates a new MultiSearchResult instance. */
    constructor($$source: Partial<MultiSearchResult> = {}) {
        if (!("keyword" in $$source)) {
            this["keyword"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("filesScanned" in $$source)) {
            this["filesScanned"] = 0;
        }
        if (!("hitCount" in $$source)) {
            this["hitCount"] = 0;
        }
        if (!("limited" in $$source)) {
            this["limited"] = false;
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MultiSearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MultiSearchResult {
        const $$createField1_0 = $$createType8;
        const $$createField5_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField5_0($$parsedSource["warnings"]);
        }
        return new MultiSearchResult($$parsedSource as Partial<MultiSearchResult>);
    }
}

export class RemoteServer {
    "name": string;
    "address": string;
    "token": string;

    /** Creates a new RemoteServer instance. */
    constructor($$source: Partial<RemoteServer> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteServer instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteServer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteServer($$parsedSource as Partial<RemoteServer>);
    }
}

export class SearchHit {
    "lineNumber": number;
    "matchLines": number[];
    "lines": LogLine[];

    /** Creates a new SearchHit instance. */
    constructor($$source: Partial<SearchHit> = {}) {
        if (!("lineNumber" in $$source)) {
            this["lineNumber"] = 0;
        }
        if (!("matchLines" in $$source)) {
            this["matchLines"] = [];
        }
        if (!("lines" in $$source)) {
            this["lines"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchHit instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchHit {
        const $$createField1_0 = $$createType9;
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("matchLines" in $$parsedSource) {
            $$parsedSource["matchLines"] = $$createField1_0($$parsedSource["matchLines"]);
        }
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField2_0($$parsedSource["lines"]);
        }
        return new SearchHit($$parsedSource as Partial<SearchHit>);
    }
}

export class SearchOptions {
    "keyword": string;
    "contextLines": number;
    "limit": number;
    "caseSensitive": boolean;
    "useRegex": boolean;
    "encoding": string;
    "startTime": string;
    "endTime": string;

    /** Creates a new SearchOptions instance. */
    constructor($$source: Partial<SearchOptions> = {}) {
        if (!("keyword" in $$source)) {
            this["keyword"] = "";
        }
        if (!("contextLines" in $$source)) {
            this["contextLines"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("caseSensitive" in $$source)) {
            this["caseSensitive"] = false;
        }
        if (!("useRegex" in $$source)) {
            this["useRegex"] = false;
        }
        if (!("encoding" in $$source)) {
            this["encoding"] = "";
        }
        if (!("startTime" in $$source)) {
            this["startTime"] = "";
        }
        if (!("endTime" in $$source)) {
            this["endTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchOptions($$parsedSource as Partial<SearchOptions>);
    }
}

export class SearchResult {
    "path": string;
    "keyword": string;
    "hits": SearchHit[];
    "hitCount": number;
    "limited": boolean;
    "scanned": number;
    "warning": string;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("keyword" in $$source)) {
            this["keyword"] = "";
        }
        if (!("hits" in $$source)) {
            this["hits"] = [];
        }
        if (!("hitCount" in $$source)) {
            this["hitCount"] = 0;
        }
        if (!("limited" in $$source)) {
            this["limited"] = false;
        }
        if (!("scanned" in $$source)) {
            this["scanned"] = 0;
        }
        if (!("warning" in $$source)) {
            this["warning"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hits" in $$parsedSource) {
            $$parsedSource["hits"] = $$createField2_0($$parsedSource["hits"]);
        }
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

export class TailUpdateResult {
    "path": string;
    "lines": LogLine[];
    "size": number;
    "truncated": boolean;
    "rotated": boolean;
    "warning": string;

    /** Creates a new TailUpdateResult instance. */
    constructor($$source: Partial<TailUpdateResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("lines" in $$source)) {
            this["lines"] = [];
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("rotated" in $$source)) {
            this["rotated"] = false;
        }
        if (!("warning" in $$source)) {
            this["warning"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TailUpdateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TailUpdateResult {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField1_0($$parsedSource["lines"]);
        }
        return new TailUpdateResult($$parsedSource as Partial<TailUpdateResult>);
    }
}

// Private type creation functions
const $$createType0 = LogFile.createFrom;
const $$createType1 = SearchHit.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = LogLine.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($$createType0);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = FileSearchResult.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($Create.Any);
